language: nix

nix: 2.2.1

script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use werbematerial-gh-pages
  - nix-build --argstr public-url "/werbematerial" -A webapp  -o result-webapp
  - nix-build --argstr public-url "/werbematerial" -A indexer -o result-indexer

after_success:
  - cachix push werbematerial-gh-pages ./result-webapp
  - cachix push werbematerial-gh-pages ./result-indexer

before_install:
    - sudo mkdir -p /etc/nix
    - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
    - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

before_cache:
    - mkdir -p $HOME/nix.store
    - nix copy --to file://$HOME/nix.store -f default.nix buildInputs

cache:
  directories:
    - $HOME/nix.store
